### ISSUE TITLE
Error message "Error in inverseA..."

### ISSUE THREAD

**Issue by zariatorres** [healyke/SIDER#17]
Hello,

I ran into an error towards the end of the SIDER code and I don't know why.  The error is:

**Error in inverseA(pedigree = pedigree, scale = scale, nodes = nodes) : 
  can't scale non-ultrametric trees**

I am looking to generate TDF values (carbon and nitrogen) for Attwater's prairie chickens (Tympanuchus cupido attwateri) blood and feather tissues.  I was able to generate TDF values using SIDER (then called DEsiR/TESIR), so I am unsure where I am going wrong here.

I've tried the example code given in the vigenettes folder "Introduction-to-SIDER.Rmd", and I don't get an error there.  

I've attached the code I used as well as the code and output produced in R.

Any advice on how to correct this error is greatly appreciated.

Thank you,
Zaria 

[APC blood Carbon script.txt](https://github.com/healyke/SIDER/files/691766/APC.blood.Carbon.script.txt)

[APC blood Carbon output.txt](https://github.com/healyke/SIDER/files/691770/APC.blood.Carbon.output.txt)

**Comment by healyke** [comment]
Hi Zaria
Thanks for raising the issue. I believe it is a problem relating to an update in one of the the ape package that loads in the phylogeny (something I have ran into in the last couple of days in separate projects also.). I will look into the problem and post when the problem is fixed. 
In the short term one way around it is to try load up the bird tree http://birdtree.org/ manually and checking if it is ultrametric using the function is.ultrametric(tree). If the tree is ultrametric the package should run fine using that phylogeny.

Cheers
Kevin

**Comment by TGuillerme** [comment]
Hi Zaria, 

As Kevin mentioned it is a problem with our bird tree example. While waiting until we fix it in the package, you can do a quick fix by adding the following just after line 19 of your script.
```{r}
    if(any(is.ultrametric(bird_trees)) == FALSE) {
      bird_trees <- lapply(bird_trees, chronoMPL)
      class(bird_trees) <- "multiPhylo"
    }
```

Cheers,
Thomas.

**Comment by zariatorres** [comment]
Hi Kevin and Thomas,

Thanks for the advice.  After adding the suggested code I got an error: 

**Error in is.ultrametric(bird_trees) : 
  object "phy" is not of class "phylo"**

I was able to to fix this by editing the code to read:

function (phy)
{
if(any(is.ultrametric(bird_trees)) == FALSE) {
      bird_trees <- lapply(bird_trees, chronoMPL)
      class(bird_trees) <- "multiPhylo"
    }
}

After that SIDER ran for me and gave me TDF values.  Was my solution to the above error correct? Both my script and output are attached.

Thanks again for the help,
Zaria 
[APC blood Carbon script.txt](https://github.com/healyke/SIDER/files/694511/APC.blood.Carbon.script.txt)
[output.txt](https://github.com/healyke/SIDER/files/694512/output.txt)

**Comment by TGuillerme** [comment]
Hi Zaria,

This is odd, the `phy` argument does not appear within the function you defined so I'm not sure how it solved the bug. Otherwise, the fact that `is.ultrametric` does not work on a `multiPhylo` object might be due to the fact that you're using a version < [`ape` 4.0](http://ape-package.ird.fr/NEWS).

Cheers,
Thomas.

**Comment by zariatorres** [comment]
Hi Thomas,

Thank you for your suggestion.  Once I updated my version the error did not come up again.

Best,
Zaria
